// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function B(a){document.cookie&&-1<document.cookie.indexOf("s=1")?(p=C("st")||p,chrome.runtime.onMessage.addListener(u),chrome.browserAction.onClicked.addListener(v),b.a0&&b.a3&&chrome.contextMenus.onClicked.addListener(w),a&&f()):(document.cookie="s=1; expires=0; path=/",chrome.runtime.onMessage.addListener(u),chrome.browserAction.onClicked.addListener(v),b.a0&&b.a3?chrome.contextMenus.removeAll(function(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},
function(){chrome.contextMenus.onClicked.addListener(w)})}):chrome.contextMenus.removeAll(function(){}),1==b.nv?x(1):"7.2.2.5"!==b.ver?(a=p,f({nv:Math.floor(Math.random()*(a+10368E5-a+1))+a,ver:"7.2.2.5"}),setTimeout(r,2012)):2<b.nv&&b.nv<p?x():a&&f())}function v(){q(function(a){a?g("https://www.mycinema.pro/menu.html"):g(chrome.runtime.getURL("nrRA.html"))})}function x(a){a?(f({nv:0}),q(function(a){a?(g("https://www.mycinema.pro/",0),g("https://www.hotcleaner.com/clickclean/install-magic.html",
0),k("siteon-install")):(k("siteoff-install"),y())})):z(1);setTimeout(r,1912)}function z(a){b.sv=1;q(function(d){d?(f(),D(),k("siteon-update")):a?setTimeout(z,3E3):(f({nv:0}),g("https://plus.google.com/110367533603365326399",0),k("siteoff-update"))})}function f(a){a&&("nv"in a&&(b.nv=a.nv),"ver"in a&&(b.ver=a.ver));var d=JSON.stringify(b);m="window.msg__='"+d+"'";try{chrome.storage.local.set({opt:d}),window.localStorage.setItem("opt",d)}catch(c){}a&&a.bub&&E(m)}function E(a){chrome.tabs.query({windowType:"normal",
url:"*://*.youtube.com/*",status:"complete"},function(d){for(var c=0,b=d.length;c<b;c++)chrome.tabs.executeScript(d[c].id,{code:a})})}function u(a,d,c){if(32==a)return-1<d.tab.index&&chrome.tabs.executeScript(d.tab.id,{code:m,runAt:"document_start"}),!1;if(0==a)return!1;if(a&&6==a.id)return F(a),!1;try{a=JSON.parse(a)}catch(l){return!1}if(0==a.id)return c({opt:b,url:d.tab.url}),!0;if(2==a.id)g(a.url,a.incognito);else if(3==a.id){for(e in a.opt)e in h&&"nv"!=e&&"ver"!=e&&(b[e]=a.opt[e]);f({bub:!0})}else if(4==
a.id){var e=a.name;if("nv"==e||"ver"==e)return!1;e in h&&(b[e]=a.value,f({bub:!0}))}else{if(5==a.id)return c({value:b[a.name]}),!0;if(7==a.id)G();else if(8==a.id)H(a.url);else{if(9==a.id)return c(A),!0;if(11==a.id)chrome.windows.update(d.tab.windowId,{state:a.v?"fullscreen":"maximized"});else if(17==a.id)f({nv:0});else if(20==a.id)k(a.ea);else if(31==a.id)return chrome.tabs.query({url:a.url},function(d){a.tab=d.length?!0:!1;c(JSON.stringify(a))}),!0}}m="window.msg__='"+JSON.stringify(b)+"'";return!1}
function F(a){A=a;chrome.tabs.query({url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html"},function(d){d&&d.length&&chrome.tabs.update(d[0].id,{active:!0},function(){chrome.tabs.sendMessage(d[0].id,a)})})}function H(a){chrome.tabs.query({url:a},function(a){a&&a.length&&chrome.tabs.update(a[0].id,{active:!0},function(){})})}function G(){q(function(a){a?(k("siteon-bgopt"),g("https://www.mycinema.pro/options.html",!1)):(k("siteoff-bgopt"),y())})}function y(){g(chrome.runtime.getURL("T.html"))}
function g(a,d){function c(a){chrome.windows.update(a.windowId,{focused:!0})}chrome.tabs.query({url:a},function(b){if(b&&b.length)chrome.tabs.update(b[0].id,{active:!0},c);else if(d)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,active:!0},c)})}catch(l){chrome.tabs.create({url:a,active:!0},c)}else chrome.tabs.create({url:a,active:!0},c)})}function w(a,d){if(7840==a.menuItemId){var b="https://www.youtube.com/results?search_query="+
encodeURIComponent(a.selectionText);0==d.url.indexOf("https://www.youtube.com/")?chrome.tabs.update({url:b}):chrome.tabs.create({url:b,selected:!0})}}function r(){t("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.2.2.5%26uc&_="+(new Date).getTime(),null,0,function(a){})}function D(){chrome.tabs.create({url:"VEFQ.html",active:!1},function(a){})}function q(a){t("HEAD","https://www.mycinema.pro/",0,"text",function(d){!d||200!=d.code&&304!=
d.code?a():a(1)})}function k(a){a=a||"unk";b.uid||(b.uid=I());t("POST","https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec=app&ea="+a+"&el=MA 7.2.2.5","text",function(){})}function t(a,d,b,e,l){var c={code:0},f=new XMLHttpRequest;f.open(a,d,!0);e&&(f.responseType=e);f.onload=function(a){c.code=this.status||0;c.data=this.response;l(c)};f.onerror=function(){l(c)};f.onabort=function(){l(c)};try{f.send(b)}catch(K){l(c)}}function I(){var a=Math.random,b=(4294967296*
a()>>>0).toString(16),c=((4294967296*a()&4294922239|16384)>>>0).toString(16),e=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>b.length&&(b=("0000000"+b).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>e.length&&(e=("0000000"+e).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[b,c.slice(0,4),c.slice(4),e.slice(0,4),e.slice(4)+a].join("-")}function C(a){a=parseInt(window.localStorage[a]);return isNaN(a)?null:a}var p=Date.now(),A,b,m,h={ver:"7.2.2.5",
nv:1,sv:0,extURL:"",uid:"",mwvc:!0,color:"yellow",mwvcm:!0,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:1,cinf:!1,cinc:0,cint:0,pt:!1,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},n=Object.getOwnPropertyDescriptor(chrome,"management");if(n){n.value={};n.configurable=!1;n.writable=!1;try{Object.defineProperty(chrome,"management",
n)}catch(a){}}try{chrome.runtime.setUninstallURL("https://www.mycinema.pro/support.html#chuhccf")}catch(a){}setTimeout(r,2712);(function(a,b,c){chrome.storage.local.get(a,function(d){try{var e=JSON.parse(a in d?d[a]:window.localStorage[a])}catch(J){e=null}c(null===e||e.constructor!==b?null:e)})})("opt",Object,function(a){b=a;if(null===b||void 0===b.ver){b=h;var d=!0}else{for(var c in b)c in h?typeof b[c]!==typeof h[c]&&(b[c]=h[c],d=!0):(delete b[c],d=!0);for(c in h)c in b||(b[c]=h[c],d=!0)}b.extURL=
chrome.runtime.getURL("");m="window.msg__='"+JSON.stringify(b)+"'";B(d)})})();
